name: Waka Readme

on:
  schedule:
    # Runs at 12am EST
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROFILE_VIEWS: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LOC_CHART: false
          ACTIONS_RUNNER_DEBUG: true
